%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 672
image_height: 376
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 491.584
   fy: 491.584
   cx: 332.997
   cy: 195.594
